server:
  port: ${HBASE_CLIENT_PORT:12088}
  servlet:
    encoding:
      charset: UTF-8
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
spring:
  application:
    name: HBASE_CLIENT
  main:
    banner-mode: off